In [5]:
import string
# package untuk perhitungan,array, dll
import numpy as np

# package untuk manipulasi data
import pandas as pd

# package untuk kebutuhan per NLP an
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

# package untuk kebutuhan Machine Learning model
# !pip install scikit-learn
from sklearn.feature_extraction.text import CountVectorizer # untuk ngubah data menjadi numerik
from sklearn.model_selection import train_test_split # untuk memisahkan data training dan testing
from sklearn.ensemble import RandomForestClassifier # kita pakai algoritma dari RandomForest (model jadi)

In [6]:
# baca data dan simpen di variable df
df = pd.read_csv('spam_ham_dataset.csv')

In [33]:
df

Unnamed: 0 label                                               text  \
0            605   ham  Subject: enron methanol ; meter # : 988291 thi...   
1           2349   ham  Subject: hpl nom for january 9 , 2001 ( see at...   
2           3624   ham  Subject: neon retreat ho ho ho , we ' re aroun...   
3           4685  spam  Subject: photoshop , windows , office . cheap ...   
4           2030   ham  Subject: re : indian springs this deal is to b...   
...          ...   ...                                                ...   
5166        1518   ham  Subject: put the 10 on the ft the transport vo...   
5167         404   ham  Subject: 3 / 4 / 2000 and following noms hpl c...   
5168        2933   ham  Subject: calpine daily gas nomination > > juli...   
5169        1409   ham  Subject: industrial worksheets for august 2000...   
5170        4807  spam  Subject: important online banking alert dear v...   

      label_num  
0             0  
1             0  
2             0  
3             1  
4             0  
...         ...  
5166          0  
5167          0  
5168          0  
5169          0  
5170          1  

[5171 rows x 4 columns]

In [8]:
df['text'] = df['text'].apply(lambda x: x.replace('\r\n',' '))

In [9]:
df.text.iloc[18]

'Subject: meter variances - ua 4 clean - up daren / vance - the two meters below are new and have unallocatable flow . . . . . . . i will need a purchase for each of them . please respond with a deal number , or further suggestions for resolution so that i can clear this up as soon as possible . mary enron on 09 / 19 / 2000 08 : 44 am - - - - - - - - - - - - - - - - - - - - - - - - - - - katherine benedict @ ect 09 / 18 / 2000 04 : 53 pm to : mary poorman / na / enron @ enron , fred boas / hou / ect @ ect , aimee lannou / hou / ect @ ect cc : subject : meter variances - ua 4 clean - up hi guys , please take a look at the following meters which are showing up with variances on my ua 4 report . once the variance has been cleared , please send me an e - mail . please try to clear these within the next couple of days . thanks , kathy benedict meter number : 9851 variance : 11 , 204 meter type : daily swing production month : august 2000 logistics contact : none volume mgmt contact : anita 

In [10]:
# download stopwords dari module/package nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/asyqari/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [11]:

# object untuk melakukan stemming kata
stemmer = PorterStemmer()
# stemmer.stem('Incorporate')

# corpus sebagai tempat nampung email yang udah di preprocessing/transform
corpus = []

# nyimpen stopwords
stopword_set = set(stopwords.words('english'))
# stopword_set


# pembersihannya
# kita akan ubah setiap kata dalam dataset
for i in range(len(df)):
    # kita ubah setiap kata jadi lowercase
    text = df['text'].iloc[i].lower()
    # kita hilangkan setiap tanda baca dan symbol
    text = text.translate(str.maketrans('','',string.punctuation)).split()
    # kita ubah setiap kata dengan stemmer
    text = [stemmer.stem(word) for word in text if word not in stopword_set]
    # kita gabungkan setiap kata tadi
    text = ' '.join(text)
    # masukan ke var corpus
    corpus.append(text)

In [12]:
# ambil contoh data dari dataset (kotor)
df.text.iloc[0]

"Subject: enron methanol ; meter # : 988291 this is a follow up to the note i gave you on monday , 4 / 3 / 00 { preliminary flow data provided by daren } . please override pop ' s daily volume { presently zero } to reflect daily activity you can obtain from gas control . this change is needed asap for economics purposes ."

In [13]:
# kita lihat versi dah di proses
corpus[0]

'subject enron methanol meter 988291 follow note gave monday 4 3 00 preliminari flow data provid daren pleas overrid pop daili volum present zero reflect daili activ obtain ga control chang need asap econom purpos'

In [14]:
# instansiasi model
vectorizer = CountVectorizer()

# kita ubah corpus yang berbentuk string ke angka
x = vectorizer.fit_transform(corpus).toarray()
y = df.label_num

# bagi data sebanyak 30 persen
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.3)
# contoh data yang sudah di ubah
x[0]

array([1, 0, 0, ..., 0, 0, 0])

In [15]:
# ini buat model ML yang dipakai (pake algo random forrest)
model = RandomForestClassifier(n_jobs=-1) #n_jobs =-1 artinya kita minta sistem pake semua CPU biar lebih cepet
# kita training model kita
model.fit(X_train,Y_train)

RandomForestClassifier(n_jobs=-1)

In [16]:
# kita lihat skor akurasinya
model.score(X_test, Y_test)

0.9768041237113402

In [26]:
# KITA COBAAAAA!

# ambil salah satu data yang ada di dataset
email_klasifikasi = df.text.values[10]
email_klasifikasi

"Subject: vocable % rnd - word asceticism vcsc - brand new stock for your attention vocalscape inc - the stock symbol is : vcsc vcsc will be our top stock pick for the month of april - stock expected to bounce to 12 cents level the stock hit its all time low and will bounce back stock is going to explode in next 5 days - watch it soar watch the stock go crazy this and next week . breaking news - vocalscape inc . announces agreement to resell mix network services current price : $ 0 . 025 we expect projected speculative price in next 5 days : $ 0 . 12 we expect projected speculative price in next 15 days : $ 0 . 15 vocalscape networks inc . is building a company that ' s revolutionizing the telecommunications industry with the most affordable phone systems , hardware , online software , and rates in canada and the us . vocalscape , a company with global reach , is receiving international attention for the development of voice over ip ( voip ) application solutions , including the award 

In [18]:
# kita lakukan preprocessing ke data tadi (bersihin dulu)
# kecilin, ilangin tandabaca/symbol
email_isi = email_klasifikasi.lower().translate(str.maketrans('','',string.punctuation)).split()
# ubah ke kata dasar
email_isi = [stemmer.stem(kata) for kata in email_isi if kata not in stopword_set]
# gabungin
email_isi = ''.join(email_isi)
# simpen
email_corpus = [email_isi]
# ubah ke bentuk angka (biner 0 1)
X_email = vectorizer.transform(email_corpus)

In [19]:
# saatnya prediksi
model.predict(X_email)

array([1])

In [20]:
# Kita tes dengan data baru diluar dari data set yang ada

# Spam email
spam_email = """
Subject: vocable % rnd - word asceticism vcsc - brand new stock for your attention vocalscape inc - the stock symbol is : 
vcsc vcsc will be our top stock pick for the month of april - stock expected to bounce to 12 cents level the stock hit its 
all time low and will bounce back stock is going to explode in next 5 days - watch it soar watch the stock go crazy this and
next week . breaking news - vocalscape inc . announces agreement to resell mix network services current price : $ 0 . 025 
we expect projected speculative price in next 5 days : $ 0 . 12 we expect projected speculative price in next 15 days : $ 0 . 15 vocalscape networks inc . is building a company that ' s 
revolutionizing the telecommunications industry with the most affordable phone systems , hardware , online software , and rates in canada and the us . vocalscape , a company with global reach , 
is receiving international attention for the development of voice over ip ( voip ) application solutions , including the award - winning eyefontm , a softphone for real - time pc - to - phone . we are an advanced implementer of pbx systems for companies , call centers , itsps and service providers . 
vocalscape has created software and interactive solutions revolving around global communications and data voice convergence . companies use vocalscape for voice over internet protocol applications like ip pbxs , softswitches , pc 2 phone and web 2 phone , providing real - time human interaction and information delivery over the internet . 
through vocalscape ' s solutions , businesses can offer a quality voice service to anywhere in the world at rates that are significantly lower than current long distance charges . we develop software to run voip networks , and sell , install and service our own branded voip gateways and gatekeeper control software . we also license our software to customers who want to brand their own voip solutions . 
vocalscape is committed to making great technology ; challenging the status quo , and building a 21 st century company that changes the way businesses communicate and interact through the internet . current price : $ 0 . 025 we expect projected speculative price in next 5 days : $ 0 . 12 we expect projected speculative price in next 15 days : $ 0 . 15 breaking news - vocalscape inc . announces agreement to resell mix network services - - - - - - - - - - katonah , n . y . , / prnewswire - firstcall 
via comtex / - - vocalscape , inc . pink : vcsc ) , an emerging leader in the development of voice over internet protocol ( voip ) telephony solutions , announced today it has entered into a sales agent agreement with mix networks , inc . a voip enhanced telephony service provider . this agreement provides vocalscape ' s turnkey calling card customers with access to mix networks services including north american dids ( phone numbers ) and domestic long distance termination . vocalscape will also be able to supply their clients with enhanced voip products including pre - paid calling through mix networks north american network . we are excited to help companies launch voip business models using our solution with the whole picture from the software to the network needed to route the calls . mix networks gives us the ability to offer wholesale monthly flat rate plans and dids to our clients that allow for us to build business models like popular voip companies such as vonage and packet 8 , says ryan gibson , vp vocalscape networks some legal words before you continue : information within this email contains forward looking statements within the meaning of section 27 a of the securities act of 1933 and section 21 b of the securities exchange act of 1934 . any statements that express or involve discussions with respect to predictions , goals , expectations , beliefs , plans , projections , objectives , assumptions or future events or performance are not statements of historical fact and may be forward looking statements . forward looking statements are based on expectations , estimates and projections at the time the statements are made that involve a number of risks and uncertainties which could cause actual results or events to differ materially from those presently anticipated . forward looking statements in this action may be identified through the use of words such as : projects , foresee , expects , estimates , believes , understands will , part of : anticipates , or that by statements indicating certain actions may , could , or might occur . all information provided within this email pertaining to investing , stocks , securities must be understood as information provided and not investment advice . emerging equity alert advises all readers and subscribers to seek advice from a registered professional securities representative before deciding to trade in stocks featured within this email . none of the material within this report shall be construed as any kind of investment advice . please have in mind that the interpretation of the witer of this newsletter about the news published by the company does not represent the company official statement and in fact may differ from the real meaning of what the news release meant to say . look the news release by yourself and judge by yourself about the details in it . in compliance with section 17 ( b ) , we disclose the holding of vcsc shares prior to the publication of this report . be aware of an inherent conflict of interest resulting from such holdings due to our intent to profit from the liquidation of these shares . shares may be sold at any time , even after positive statements have been made regarding the above company . since we own shares , there is an inherent conflict of interest in our statements and opinions . readers of this publication are cautioned not to place undue reliance on forward - looking statements , which are based on certain assumptions and expectations involving various risks and uncertainties , that could cause results to differ materially from those set forth in the forward - looking statements . please be advised that nothing within this email shall constitute a solicitation or an invitation to get position in or sell any security mentioned herein . this newsletter is neither a registered investment advisor nor affiliated with any broker or dealer . this newsletter was paid $ 49000 from third party to send this report . all statements made are our express opinion only and should be treated as such . we may own , take position and sell any securities mentioned at any time . this report includes forward - looking statements within the meaning of the private securities litigation reform act of 1995 . these statements may include terms as projected speculative price expect , believe , may , will , soar move , undervalued and intend or similar terms .
"""

# Non-spam email
non_spam_email = """
Subject: meter variances - ua 4 clean - up daren / vance - the two meters below are new and have unallocatable flow . . . . . . . 
i will need a purchase for each of them . please respond with a deal number , or further suggestions for resolution so 
that i can clear this up as soon as possible . mary enron on 09 / 19 / 2000 08 : 44 am - - - - - - - - - - - - - - - - - - - - - - - - - - - katherine benedict @ ect 09 / 18 / 2000 04 : 53 pm to : mary poorman / na / 
enron @ enron , fred boas / hou / ect @ ect , aimee lannou / hou / ect @ ect cc : subject : meter variances - ua 4 clean - up hi guys , please take a look at 
the following meters which are showing up with variances on my ua 4 report . once the variance has been cleared , please send me an e - mail . 
please try to clear these within the next couple of days . thanks , kathy benedict meter number : 9851 variance : 11 , 204 meter type : daily swing production month : 
august 2000 logistics contact : none volume mgmt contact : anita luong meter number : 9852 variance 568 meter type : daily swing production month : august 2000 logistics contact : none volume mgmt contact : anita luong
"""

In [21]:
# kita lakukan preprocessing ke data tadi (bersihin dulu)
# kecilin, ilangin tandabaca/symbol
spam_isi = spam_email.lower().translate(str.maketrans('','',string.punctuation)).split()
# ubah ke kata dasar
spam_isi = [stemmer.stem(kata) for kata in spam_isi if kata not in stopword_set]
# # gabungin
spam_isi = ' '.join(spam_isi)
spam_isi
# simpen
spam_corpus = [spam_isi]
# ubah ke bentuk angka (biner 0 1)
X_email = vectorizer.transform(spam_corpus)

In [22]:
# saatnya prediksi
model.predict(X_email)

array([1])

In [23]:
# kita lakukan preprocessing ke data tadi (bersihin dulu)
# kecilin, ilangin tandabaca/symbol
nonSpam_isi = non_spam_email.lower().translate(str.maketrans('','',string.punctuation)).split()
# ubah ke kata dasar
nonSpam_isi = [stemmer.stem(kata) for kata in nonSpam_isi if kata not in stopword_set]
# gabungin
nonSpam_isi = ' '.join(nonSpam_isi)
nonSpam_isi

'subject meter varianc ua 4 clean daren vanc two meter new unallocat flow need purchas pleas respond deal number suggest resolut clear soon possibl mari enron 09 19 2000 08 44 katherin benedict ect 09 18 2000 04 53 pm mari poorman na enron enron fred boa hou ect ect aime lannou hou ect ect cc subject meter varianc ua 4 clean hi guy pleas take look follow meter show varianc ua 4 report varianc clear pleas send e mail pleas tri clear within next coupl day thank kathi benedict meter number 9851 varianc 11 204 meter type daili swing product month august 2000 logist contact none volum mgmt contact anita luong meter number 9852 varianc 568 meter type daili swing product month august 2000 logist contact none volum mgmt contact anita luong'

In [24]:
# simpen
nonSpam_corpus = [nonSpam_isi]
# ubah ke bentuk angka (biner 0 1)
X_email = vectorizer.transform(nonSpam_corpus)

In [25]:
# saatnya prediksi
model.predict(X_email)

array([0])